/* 由 tools.py TOOL_META 导出（scripts/export_ai_schemas.py），勿手改。字段: name, readonly, side_effect, risk, long_running */
typedef struct { const char *name; int readonly; const char *side_effect; const char *risk; int long_running; } ai_tool_meta;
static const ai_tool_meta K_TOOL_META[] = {
{"ask_user", 1, "none", "low", 0},
{"get_launcher_state", 1, "none", "low", 0},
{"list_instances", 1, "none", "low", 0},
{"list_installed_versions", 1, "none", "low", 0},
{"search_versions", 1, "network", "low", 0},
{"search_mods", 1, "network", "low", 0},
{"search_modpacks", 1, "network", "low", 0},
{"list_mods", 1, "read", "low", 0},
{"install_game", 0, "write_local", "high", 1},
{"install_mod", 0, "write_local", "medium", 1},
{"install_modpack", 0, "write_local", "high", 1},
{"install_shader", 0, "write_local", "low", 1},
{"install_resourcepack", 0, "write_local", "low", 1},
{"install_datapack", 0, "write_local", "low", 1},
{"search_content", 1, "network", "low", 0},
{"search_worlds", 1, "network", "low", 0},
{"install_world", 0, "write_local", "medium", 1},
{"create_instance", 0, "write_local", "medium", 0},
{"delete_instance", 0, "delete", "high", 0},
{"delete_mod", 0, "delete", "high", 0},
{"disable_mod", 0, "write_local", "medium", 0},
{"enable_mod", 0, "write_local", "medium", 0},
{"get_java_list", 1, "none", "low", 0},
{"download_java", 0, "write_local", "medium", 1},
{"launch_game", 0, "launch", "high", 0},
{"diagnose_launch", 1, "read", "low", 0},
{"get_latest_log", 1, "read", "low", 0},
{"get_crash_report", 1, "read", "low", 0},
{"scan_mod_conflicts", 1, "read", "low", 0},
{"inspect_mod", 1, "read", "low", 0},
{"list_mod_configs", 1, "read", "low", 0},
{"read_mod_config", 1, "read", "low", 0},
{"write_mod_config", 0, "write_local", "high", 0},
{"read_artifact", 1, "read", "low", 0},
{"dispatch_subagent", 1, "none", "low", 0},
{"update_plan", 1, "none", "low", 0},
    {NULL, 0, "", "", 0}
};
